env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo

task:
    name: aosp # Project name
    timeout_in: 120m # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      image: apon77/aosp:latest
      cpu: 1 
      memory: 24G
    sync_script: # To sync source
      - ./sync # Source sync script
    build_script: # Actual build script foreground
      - ./build # Build script to run
